### ISSUE TITLE
LRU crawler?

### ISSUE THREAD

**Issue by dormando** [quora/mcinspector#1]
Slightly confused; there's an LRU crawler in memcached for a very long time which culls out expired items. Does this not work for you?

**Comment by fusiyuan2010** [comment]
Hi @dormando ,  I developed this software and put it into use much earlier than its being open sourced. At that time, the LRU crawler feature was just released and our production were running the even older version of memcached.  We anyway periodically dump internal stats of memcached by this tool, expire item cleaning is a by product of this procedure and it works pretty well, so I didn't bother to try this feature later.

**Comment by dormando** [comment]
Interesting. Any chance I could convince you to leave a note somewhere saying that it isn't required in mainline? People tend to run across these things and take them as meaning there's no other way to do it. would be much appreciated!

**Comment by fusiyuan2010** [comment]
@dormando  I added a note at the 'Clean expired objects' section in README.md.

**Comment by dormando** [comment]
thanks!
